In [1]:
import numpy as np

In [2]:
def sigmoid(z):
    return 1.0/(1.0+np.exp(-z))

def sigmoid_prime(z):
    return sigmoid(z)*(1 - sigmoid(z))

In [3]:
inputs = np.array([0, 1, 1])
weightsS = np.array([[0.7, 0.2, 0.7],[0.8, 0.3, 0.6]])
weightsO = np.array([[0.2, 0.4]])

In [4]:
sumS = weightsS @ inputs
outS = np.array([[max(sumS[0], 0)], [sigmoid(sumS[1])]])
print(outS)
max_prime = 1 if outS[0,0] > 0 else 0 
sumO = weightsO @ outS
outputs = sigmoid(sumO)
print(outputs)

[[0.9      ]
 [0.7109495]]
[[0.61405267]]


In [10]:
errorO = (outputs - 1) * sigmoid_prime(sumO)
errorI_2 = (weightsO.T @ errorO)[1] * sigmoid_prime(sumS)[1]
errorI_1 = (weightsO.T @ errorO)[0]

In [12]:
errorO 

array([[-0.09146642]])

In [13]:
errorI_1

array([-0.01829328])

In [14]:
errorI_2

array([-0.00751855])